# Generated by Django 5.0.1 on 2024-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_file_remove_post_file_in_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='blog.category'),
        ),
    ]
