# Generated by Django 5.0.1 on 2024-03-14 12:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
    ]
